### PR TITLE
Update vendored deps so we get the most recent prometheus functions

### PR DESCRIPTION
**Pull request by rbarry82**
## Issue
`promql-transform` cannot currently recognize `last_over_time()` and probably some other functions.

## Solution
Update the vendored deps.

## Release Notes
Update to the latest version of `github.com/prometheus/prometheus/promql`

### CODE REVIEW

**Comment by mmanciop** [comment]
I am a bit ambivalent about updating the version of promql supported by promql-transform ahead of the version in the ROCK that we use in the prometheus-k8s charm. @simskij wdyt?

**Comment by rbarry82** [comment]
> I am a bit ambivalent about updating the version of promql supported by promql-transform ahead of the version in the ROCK that we use in the prometheus-k8s charm. @simskij wdyt?

I mean, that could be updated also...

The real reason for this was in throwing ~1000 expressions I pulled out of dashboards I have in my environment and seeing where `promql-transform` failed, what was just Grafana stuff, what was not. There are a [fair number of functions missing from the current version](https://github.com/canonical/promql-transform/pull/6/files#diff-d21ff4146333e787153f8cefe7622f20b00b57ec2b14d44462e2e0f1cc5f5fd6R42), some of which (`last_over_time()`, `present_over_time()`) are actually used in "real-world" dashboards.

**Comment by simonaronsson** [comment]
> I am a bit ambivalent about updating the version of promql supported by promql-transform ahead of the version in the ROCK that we use in the prometheus-k8s charm. @simskij wdyt?

Prior to me having an opinion, I would suggest @rbarry82 try to run the expressions in the Prometheus UI and omit the ones not working there either, then run the same test of `promql-transform` with the remaining ones.

**Comment by simonaronsson** [comment]
I'm closing this for now with the motivation being that we should stay in sync with the version used in the Prometheus charm.

**Pull request closed without merging**
